### ISSUE TITLE
update-pok3r-rgb-firmware-on-macos

### ISSUE THREAD

**Issue by philihp** [sonph/sonph.github.io#22]
any reason why 2016-08-17-update-pok3r-rgb-firmware-on-macos.md was removed?

**Comment by sonph** [comment]
hah i kind of decided that blogging isn't really for me so i archived these posts. if you found the instructions helpful, i'm glad. feel free to post that some where.

**Comment by philihp** [comment]
lol, aww man... i did :) sorry to see your writing go. hope it comes back someday!
